spring.application.name=StudentManagement
spring.config.import=optional:classpath:application-secret.properties
spring.devtools.restart.enabled=false

# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=students_management;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}

# SQL Server Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL Server Dialect
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Secret
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

#Telegram
telegram.baseUrl=https://api.telegram.org
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

#JsonPlaceholder
jsonplaceholder.baseUrl=https://jsonplaceholder.typicode.com

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cloud.compatibility-verifier.enabled=true
spring.data.redis.repositories.enabled=false

#Redis Cache TTL
cache.ttl.student=1
cache.ttl.students=50

#Resilience4j
#Retry
resilience4j.retry.instances.jsonPlaceholderClient.max-attempts=5
resilience4j.retry.instances.jsonPlaceholderClient.wait-duration=500ms
resilience4j.retry.retry-aspect-order=2

#TimeLimiter
resilience4j.timelimiter.instances.jsonPlaceholderClient.timeout-duration=5s
resilience4j.timelimiter.instances.jsonPlaceholderClient.cancel-running-future=true
resilience4j.timelimiter.time-limiter-aspect-order=3

#CircuitBreaker
resilience4j.circuitbreaker.instances.jsonPlaceholderClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.jsonPlaceholderClient.sliding-window-size=5
resilience4j.circuitbreaker.instances.jsonPlaceholderClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.jsonPlaceholderClient.wait-duration-in-open-state=3s
resilience4j.circuitbreaker.instances.jsonPlaceholderClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1