spring.application.name=StudentManagement

# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=students_management;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123!

# SQL Server Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL Server Dialect
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Secret
jwt.secret=oP6VoJOPfhA7VRskPmdSV8gyTNkbY50nyXqqJdjuHlA=
jwt.expiration=3600000

#Telegram
telegram.bot.token=6881258383:AAF3Ebp6PfHi_zsclwX7KawZgu6QjvX7zBQ

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379